project:
  type: website
  output-dir: docs

website:
  sidebar:
    logo: img/ntu_logo.png
    title: "Research Methods & Data Analyses"
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - text: Module Overview
        href: pages/overview.qmd
      - section: Content
        contents:
          - href: pages/intro.qmd
            text: Week 1 - Introduction
          - href: workbook.qmd
            text: Week 2 - Workbook
          - href: data_wrang.qmd
            text: Week 3 - Data Wrangling
          - href: explor_anal.qmd
            text: Week 4 - Exploratory Analyses
  page-footer:
    left: Learn more about the
    right: Source code available on
          

format:
  html:
    theme: styles.scss
    #css: styles.css
    toc: false
    page-layout: full