project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

website:
  navbar:
    background: light
    logo: img/ntu_logo.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Get Started"
        menu:
          - text: "1 - Install R and Rstudio"
            icon: "emoji-sunglasses-fill"
            href: get-started/1-install.qmd
          - text: "2 - Basic Introduction to R and Rstudio"
            icon: "tools"
            href: get-started/2-basic-intro.qmd
          - text: "3 - Syntax & Data Structures"
            icon: "tools"
            href: get-started/3-syntax.qmd
          - text: "4 - Functions and Arguments"
            icon: "tools"
            href: get-started/4-functions.qmd
          - text: "5 - Reading data in R"
            icon: "tools"
            href: get-started/5-data.qmd
      - text: "Content"
        href: sessions/index.qmd
      - text: "Bibliography"
        href: bibliography/index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "Assessment"
        href: assessment.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/quarto-dev/quarto-cli/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/quarto-dev/quarto-cli/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        text: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        text: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        text: Quarto Blog RSS
  
 
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})
          

format:
  html:
    theme: styles.scss
    #css: styles.css
    toc: false
    page-layout: full