---
title: "Research Methods & Data Analyses"
title-block-banner: "#9e043d"
subtitle: "Stats, Coding, Data Science and more"
details: |
  ARES40011 • Autumn 2025<br>School of Animal Rural and Environmental Sciences<br>Nottingham Trent University
sidebar: false
toc: false
page-layout: full
format:
  html:
    template-partials:
      - html/home/title-block.html
course-logo: img/course_logo.png
---

::::::: home
:::::: {.grid .course-details}
::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
### Instructor

-   {{< fa user >}} [{{< var instructor.name >}}]({{< var instructor.url >}})
-   {{< fa university >}} {{< var instructor.office >}}
-   {{< fa envelope >}} <a href='mailto:{{< var instructor.email >}}'>{{< var instructor.email >}}</a>
-   <i class="fa-brands fa-bluesky"></i> [Bluesky]({{< var instructor.bluesky >}})
:::

::: {.g-col-12 .g-col-sm-6 .g-col-md-4}
### Course details

-   {{< fa calendar >}} {{< var course.days >}}
-   {{< fa calendar-alt >}} {{< var course.dates >}}
-   {{< fa clock >}} {{< var course.time >}}
-   {{< fa location-dot >}} {{< var course.location >}}
:::

::: {.g-col-12 .g-col-md-4 .contact-policy}
### Contacting

Doubts and enquires are preferably brought to tutorial sessions and shared in our dedicated [Teams Channel](https://teams.microsoft.com/v2/).
:::
::::::
:::::::

## Welcome

We hope this module will be an opportunity to enhance your critical and analytical skills, required for your future careers. This module is the only core module across all PG provision at ARES, reflecting its underpinning importance for your courses. It also gives you a great opportunity to meet colleagues with different interests and to broaden your own horizons.

We have tried to make this module as accessible as possible, knowing that some of the content is challenging. We have based all materials in our own research expertise, we are not statisticians, rather we are statistic users, just like you!

We are looking forward to meeting you all
